[package]
name = "zk-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
jiff = "0.2"
nucleo = { version = "0.5", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
thiserror = "2"

[dev-dependencies]
anyhow = "1.0.101"
tempfile = "3"
